name: Deploy Python package to Azure Web App as a Linux web app.
on:
  push:
   branches:    
      - 'test',
      - 'stage'

variables:
  isTest: $[eq(variables['Build.SourceBranch'], 'refs/heads/test')],
  isStage: $[eq(variables['Build.SourceBranch'], 'refs/heads/stage')]

env:
  AZURE_WEBAPP_NAME: "webapp-swapnilkumar-f1" # set this to your application's name
  WORKING_DIRECTORY: '.'         # set this to the path to your path of working directory inside github repository, defaults to the repository root
  PYTHON_VERSION: '3.8' 
  STARTUP_COMMAND: 'gunicorn --bind=0.0.0.0 --timeout 600 run:app'           # set this to the startup command required to start the gunicorn server. default it is empty

stages:
  - stage: 'test'
    condition: isTest
    jobs:
      build-and-deploy:
  runs-on: ubuntu-latest
  environment: dev
  steps:
  # checkout the repo 
  - uses: actions/checkout@master
  
  # setup python
  - name: Setup Python
    uses: actions/setup-python@v1
    with:
     python-version: ${{ env.PYTHON_VERSION }}

  # install dependencies
  - name: python install
    working-directory: ${{ env.WORKING_DIRECTORY }}
    run: |
     sudo apt install python${{ env.PYTHON_VERSION }}-venv
     python -m venv --copies antenv
     source antenv/bin/activate
     pip install setuptools
     pip install -r requirements.txt
     
     
  # Azure login
  - uses: azure/login@v1
    with:
     creds: ${{ secrets.AZURE_CREDENTIALS }}
  - uses: azure/appservice-settings@v1
    with:
     app-name: ${{ env.AZURE_WEBAPP_NAME }}
     mask-inputs: false
     general-settings-json: '{"linuxFxVersion": "PYTHON|${{ env.PYTHON_VERSION }}"}' #'General configuration settings as Key Value pairs'
     
     
  # deploy web app
  - uses: azure/webapps-deploy@v2
    with:
     app-name: ${{ env.AZURE_WEBAPP_NAME }}
     package: ${{ env.WORKING_DIRECTORY }}
     startup-command: ${{ env.STARTUP_COMMAND }}
  # Azure logout
  - name: logout
    run: |
     az logout

